# map
enable_draw_nodes: False
enable_draw_links: False
max_link_len: 80
set_links_policy: 3
nodes_show_policy: 1

# particle
rand_pos_range: 512
match_weight_policy: 1
estim_pos_policy: 1

# particle filter
begin: "2000-01-01 00:00:00"
end: "2000-01-01 23:59:59"
enable_truth: False

map_img_file: sample.pgm
map_conf_file: sample.yaml
enable_clear_map: True
enable_draw_beacons: False
map_show_policy: 1

particle_num: 256
init_pos: [0, 0]
init_pos_sd: 16
init_direct: 0
init_direct_sd: 45
max_particle_stride: 32
direct_sd: 4.5
lost_resample_policy: 2

win_size: 2
win_stride: 1
win_policy: 1

enable_save_video: False
enable_save_img: False
file_name:
frame_rate: 1

propag_coef: 4
el_correction: 2
dist_sd: 64
