begin: "2000-01-01 00:00:00"
end: "2000-01-01 23:59:59"
log_file: foo_ble.csv
init_direct: 0
init_direct_sd: 0
init_pos: [0, 0]
init_pos_sd: 0
lost_tj_policy: 1
particle_num: 128
result_dir_name:

win_size: 2

beacon_dir: foo_beacon
enable_clear_map: True
enable_draw_beacons: False
enable_save_img: False
enable_save_video: False
frame_rate: 1
map_conf_file: foo_map.yaml
map_img_file: foo_map.pgm
map_show_policy: 3
map_show_range:
win_stride: 1

direct_sd: 1
max_particle_stride: 25
rand_pos_range: 375

lost_resample_policy: 1

truth_log_file:

dist_sd: 37.5
el_correction: 2
enable_write_conf: False
estim_pos_policy: 2
neg_weight_coef: 0
propag_coef: 5

win_policy: 1

enable_draw_links: False
enable_draw_nodes: False
max_link_len: 75
nodes_show_policy: 1
set_nodes_links_policy: 3

match_weight_policy: 4
