begin: "2000-01-01 00:00:00"
end: "2000-01-01 23:59:59"
log_file: "sample_ble.csv"
init_direct: 0
init_direct_sd: 45
init_pos: [0, 0]
init_pos_sd: 16
particle_num: 256

win_size: 2

enable_clear_map: True
enable_draw_beacons: False
enable_save_img: False
enable_save_video: False
frame_rate: 1
map_conf_file: sample.yaml
map_img_file: sample.pgm
map_show_policy: 1
result_file_name:
win_stride: 1

direct_sd: 4.5
max_particle_stride: 32
rand_pos_range: 512

lost_resample_policy: 1

truth_log_file:

dist_sd: 64
el_correction: 2
estim_pos_policy: 1
neg_weight_coef: 0
propag_coef: 4

win_policy: 1

enable_draw_links: False
enable_draw_nodes: False
max_link_len: 80
nodes_show_policy: 1
set_links_policy: 3

match_weight_policy: 1
