begin: "2022-01-07 13:43:54"
end: "2022-01-07 13:54:19"
log_file: hcii2022_ble.csv
init_direct: 270
init_direct_sd: 0
init_pos: [1155, 1000]
init_pos_sd: 0
lost_tj_policy: 2
particle_num: 128
result_dir_name: sample

win_size: 2

beacon_dir: hcii2022_beacon
enable_clear_map: True
enable_draw_beacons: True
enable_save_img: True
enable_save_video: True
frame_rate: 1
map_conf_file: hcii2022_map.yaml
map_img_file: hcii2022_map.pgm
map_show_policy: 3
map_show_range: [[300, 1425], [800, 1550]]
win_stride: 1

direct_sd: 1
max_particle_stride: 25
rand_pos_range: 375

lost_resample_policy: 1

truth_log_file: hcii2022_truth.pkl

dist_sd: 37.5
el_correction: 2
enable_write_conf: True
estim_pos_policy: 2
neg_weight_coef: 0
propag_coef: 5

win_policy: 1

enable_draw_links: False
enable_draw_nodes: False
max_link_len: 75
nodes_show_policy: 1
set_nodes_links_policy: 3

match_weight_policy: 4
